name: Publish to Hangar and Modrinth
on:
  push:
    branches:
      - master
      - dev

jobs:
  publish:
    if: github.repository_owner == 'ViaVersion'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get and Check Commit Message
        id: commit_check
        run: |
          commit_message=$(git log -1 --pretty=%B)
          skip_check=$(echo $commit_message | grep -E '^\[ci skip\]')
          if [ "$skip_check" != "" ]; then
            echo "Commit message contains [ci skip], skipping publish"
          fi
          echo "::set-output name=skip::$skip_check"
        continue-on-error: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: 17
      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          if [ "${{ steps.commit_check.outputs.skip }}" == "" ]; then
            ./gradlew publishAllPublicationsToHangar
          fi
